from datatyp import course, room, timeslot

courses_data = [
    course("aljabar linier dan geometri",
           ["Ramadhan Paninggalih"],
           jumlah_class=3),
    course("arsitektur komputer",  
           ["Aninditya Anggari Nuryono",  
            "Aninditya Anggari Nuryono",  
            "Riska Kurniyanto Abdullah"],  
           jumlah_class=3),
    course("deep learning",  
           ["Boby Mugi Pratama"],  
           jumlah_class=1), 
    course("desain web",  
           ["Rizal Kusuma Putra"],  
           jumlah_class=2), 
    course("Implementasi dan Pengujian Perangkat Lunak",  
           ["Nur Fajri Azhar"], 
           jumlah_class=3), 
    course("interaksi manusia dan komputer",  
           ["Nisa Rizqiya Fadhliana"],  
           jumlah_class=3), 
    course("Keamanan Siber (Pengayaan)",  
           ["Darmansyah"],  
           jumlah_class=1), 
    course("Kecerdasan Web",  
           ["Gusti Ahmad Fanshuri Alfarisy"], 
           jumlah_class=1), 
    course("keprofesian informatika",  
           ["Nur Fajri Azhar",  
            "Darmansyah"],  
           jumlah_class=2), 
    course("Komputasi Evolusioner",  
           ["Muchammad Chandra Cahyo Utomo"], 
           jumlah_class=1),  
    course("Manajemen Basis Data",  
           ["Bowo Nugroho"],  
           jumlah_class=3), 
    course("Manajemen Proyek TIK",  
           ["Riska Kurniyanto Abdullah"], 
           jumlah_class=1), 
    course("matematika diskrit", 
           ["Ramadhan Paninggalih"], 
           jumlah_class=2), 
    course("Pemrograman Fungsional", 
           ["Gusti Ahmad Fanshuri Alfarisy"], 
           jumlah_class=2), 
    course("Pemrosesan Bahasa Alami", 
           ["Bima Prihasto"],  
           jumlah_class=1), 
    course("pengantar informatika", ["Muchammad Chandra Cahyo Utomo"], 
           jumlah_class=2), 
    course("pengantar kecerdasan artifisial", 
           ["Bima Prihasto", 
            "Bima Prihasto",  
            "Gusti Ahmad Fanshuri Alfarisy"],  
           jumlah_class=3), 
    course("Pengembangan Aplikasi Perangkat Bergerak", 
           ["Rizal Kusuma Putra"],  
           jumlah_class=2), 
    course("Pengolahan Citra Digital", 
           ["Rizky Amelia"],  
           jumlah_class=2), 
    course("Proposal Tugas Akhir", 
           ["Nisa Rizqiya Fadhliana"], 
           jumlah_class=1), 
    course("Sains Data (Pengayaan)",  
           ["Ramadhan Paninggalih"],  
           jumlah_class=1), 
    course("sistem digital",  
           ["Boby Mugi Pratama"],  
           jumlah_class=3), 
    course("sistem operasi", 
           ["Darmansyah"], 
           jumlah_class=3), 
    course("Sistem Paralel dan Terdistribusi", 
           ["Riska Kurniyanto Abdullah"],
           jumlah_class=2), 
    course("struktur data", 
           ["Muchammad Chandra Cahyo Utomo",  
            "Muchammad Chandra Cahyo Utomo", 
            "Bowo Nugroho"], 
           jumlah_class=3), 
    course("Visi Komputer",  
           ["Rizky Amelia"], 
           jumlah_class=1), 
 
]

rooms_data = [ 
    room("A-105", 80, {17}), 
    room("A-308", 80, {6, 12}), 
    room("B-102", 40, {14}), 
    room("B-103", 40, {1,6,9,11,14,15,19}), 
    room("B-106", 40, {10,18}), 
    room("E-101", 40, {11,12}), 
    room("E-102", 80, {15}), 
    room("E-103", 40, {3,6,7,19}), 
    room("E-104", 60, {7,19}), 
    room("E-105", 40, {6,16}), 
    room("E-201", 60, {13,19}), 
    room("E-202", 80, {2,13}), 
    room("E-204", 60, {13,19}), 
    room("E-205", 80, {2,15}), 
    room("E-206", 40, {10,14}), 
    room("E-301", 60, {2,3,19}), 
    room("E-302", 40, {14}), 
    room("E-303", 40, {13,19}), 
    room("E-304", 40, {8}), 
    room("E-305", 100, {3,4,7,9,12}), 
    room("E-306", 40, {8,13}), 
    room("E-307", 40, {1,8,12,16,18}), 
    room("F-103", 40, {1}), 
]

timeslots_data = [ 
    # Senin 
    timeslot(1, "Senin", "07:30 - 10:00"), 
    timeslot(2, "Senin", "10:20 - 12:00"), 
    timeslot(3, "Senin", "13:00 - 15:30"), 
    timeslot(4, "Senin", "16:00 - 17:30"), 
 
    # Selasa 
    timeslot(5, "Selasa", "07:30 - 10:00"), 
    timeslot(6, "Selasa", "10:20 - 12:00"), 
    timeslot(7, "Selasa", "13:00 - 15:30"), 
    timeslot(8, "Selasa", "16:00 - 17:30"), 
 
    # Rabu 
    timeslot(9, "Rabu", "07:30 - 10:00"), 
    timeslot(10, "Rabu", "10:20 - 12:00"), 
    timeslot(11, "Rabu", "13:00 - 15:30"), 
    timeslot(12, "Rabu", "16:00 - 17:30"), 
 
    # Kamis 
    timeslot(13, "Kamis", "07:30 - 10:00"), 
    timeslot(14, "Kamis", "10:20 - 12:00"), 
    timeslot(15, "Kamis", "13:00 - 15:30"), 
    timeslot(16, "Kamis", "16:00 - 17:30"), 
 
    # Jumat 
    timeslot(17, "Jumat", "07:30 - 9:00"), 
    timeslot(18, "Jumat", "9:20 - 11:00"), 
    timeslot(19, "Jumat", "13:00 - 15:30"), 
    timeslot(20, "Jumat", "16:00 - 17:30"), 
]